grpc:
  port: "8080"
  users_service_address: "users-service:8080"

rabbitmq:
  notifications_queue: "notifications"
  email_queue: "email"

redis:
  tokens_ttl: "10m"
  address: "redis:6379"
  password: ${APP_REDIS_PASSWORD}
  db: 0

postgres:
  user: ${APP_POSTGRES_USER}
  name: ${APP_POSTGRES_NAME}
  password: ${APP_POSTGRES_PASSWORD}
  address: ${APP_POSTGRES_ADDRESS}

logging:
  isProduction: ${APP_LOGGING_IS_PRODUCTION}
  vectorURL: "http://infrastructure_vector_1:9880"
